plugins {
    id 'net.neoforged.moddev' version '2.0.142'
    id 'com.modrinth.minotaur' version '2.+'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = neoforge_version

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all',
                '--output', file('src/generated/resources/').absolutePath,
                '--existing', file('src/main/resources/').absolutePath
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
}

dependencies {
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "tinyblocks"
    versionNumber = mod_version
    versionType = "release"
    uploadFile = jar
    gameVersions = ["1.21.1"]
    loaders = ["neoforge"]
    changelog = System.getenv("CHANGELOG") ?: ""
}
