org.gradle.jvmargs=-Xmx3g
org.gradle.daemon=true

minecraft_version=1.21.1
neoforge_version=21.1.244
mod_id=tinyblocks
mod_name=TinyBlocks
mod_version=1.0.0
mod_group_id=com.therappha.tinyblocks
mod_authors=therappha
mod_description=Place and interact with blocks at 1/8 to 1/16 scale inside a single block space.
mod_license=CC-BY-NC-SA-4.0
