modLoader = "javafml"
loaderVersion = "[4,)"
license = "CC-BY-NC-SA-4.0"

[[mods]]
    modId = "tinyblocks"
    version = "${file.jarVersion}"
    displayName = "TinyBlocks"
    authors = "therappha"
    description = '''
Subgrid engine for NeoForge 1.21.1 — place and interact with blocks at 1/8 or 1/16 scale inside a single block space.
'''

[[dependencies.tinyblocks]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.tinyblocks]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,1.22)"
    ordering = "NONE"
    side = "BOTH"

